services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=promptbook
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - promptbook-network

networks:
  promptbook-network:
    driver: bridge

volumes:
  mysqldata:
